// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUpxhQiQBNPzFrlk3Yt-LOS-mdtpytfU',
    appId: '1:463350298466:web:76f67b05ede0c05ca4de3b',
    messagingSenderId: '463350298466',
    projectId: 'your-trip-c3937',
    authDomain: 'your-trip-c3937.firebaseapp.com',
    databaseURL: 'https://your-trip-c3937-default-rtdb.firebaseio.com',
    storageBucket: 'your-trip-c3937.appspot.com',
    measurementId: 'G-5GBQ4EJC5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFlOq9iK8RegBFlku0AaRkDvHkZVYVgw',
    appId: '1:463350298466:android:ec8cddfff0bf8a50a4de3b',
    messagingSenderId: '463350298466',
    projectId: 'your-trip-c3937',
    storageBucket: 'your-trip-c3937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMTZAj6_eXwmA5HNZ9n0CnDQhvxgA-Fs',
    appId: '1:463350298466:ios:01ce5007914f82dda4de3b',
    messagingSenderId: '463350298466',
    projectId: 'your-trip-c3937',
    storageBucket: 'your-trip-c3937.appspot.com',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMTZAj6_eXwmA5HNZ9n0CnDQhvxgA-Fs',
    appId: '1:463350298466:ios:42968461639a6b57a4de3b',
    messagingSenderId: '463350298466',
    projectId: 'your-trip-c3937',
    storageBucket: 'your-trip-c3937.appspot.com',
    iosBundleId: 'com.example.temp.RunnerTests',
  );
}
