// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZufFs-LZ1gd_OkJoH7sXLUBgP5KP0FYk',
    appId: '1:830682312188:web:862912ac9f7ed5ecd99679',
    messagingSenderId: '830682312188',
    projectId: 'your-trip-586b7',
    authDomain: 'your-trip-586b7.firebaseapp.com',
    databaseURL: 'https://your-trip-586b7-default-rtdb.firebaseio.com',
    storageBucket: 'your-trip-586b7.appspot.com',
    measurementId: 'G-96HCK3MN8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVbCT_jG2e9a4g-syb6oT1azX0-tpSQI',
    appId: '1:830682312188:android:be710df0b000982ad99679',
    messagingSenderId: '830682312188',
    projectId: 'your-trip-586b7',
    databaseURL: 'https://your-trip-586b7-default-rtdb.firebaseio.com',
    storageBucket: 'your-trip-586b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOhpPnsSGJfw97SYtkltTvFyStdGPFcg',
    appId: '1:830682312188:ios:df091874a03d4ecad99679',
    messagingSenderId: '830682312188',
    projectId: 'your-trip-586b7',
    databaseURL: 'https://your-trip-586b7-default-rtdb.firebaseio.com',
    storageBucket: 'your-trip-586b7.appspot.com',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxOhpPnsSGJfw97SYtkltTvFyStdGPFcg',
    appId: '1:830682312188:ios:0b6093b60da167b5d99679',
    messagingSenderId: '830682312188',
    projectId: 'your-trip-586b7',
    databaseURL: 'https://your-trip-586b7-default-rtdb.firebaseio.com',
    storageBucket: 'your-trip-586b7.appspot.com',
    iosBundleId: 'com.example.temp.RunnerTests',
  );
}
